### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by mrneo240** [AbandonedCart/reicast-emulator-lk#5]
http://loungekatt.sytes.net:3194/Dreamcast/report/logs/1518833005256.txt

**Comment by LoungeKatt** [comment]
`/data/app/com.reicast.emulator-1/lib/arm/libdc.so has text relocations. This is wasting memory and prevents security hardening. Please fix.`

This is a known issue on the main repository. Unfortunately, there is no workaround at this time.

**Comment by LoungeKatt** [comment]
This should be resolved by a workaround that turns the crash into a notification.
